enum BridgeTelemetrySlice: String, CaseIterable, Codable, Equatable, Hashable, Sendable {
    case diffStatus = "diff_status"
    case diffFiles = "diff_files"
    case reviewThreads = "review_threads"
    case reviewViewedFiles = "review_viewed_files"
    case reviewSnapshot = "review_snapshot"
    case reviewDelta = "review_delta"
    case reviewInvalidation = "review_invalidation"
    case reviewReset = "review_reset"
    case connectionHealth = "connection_health"
    case commandAcks = "command_acks"
    case reviewRPC = "review_rpc"
    case contentFetch = "content_fetch"
    case reviewProjection = "review_projection"
    case treePrepareInput = "tree_prepare_input"
    case codeViewItem = "code_view_item"
    case codeViewScroll = "code_view_scroll"
    case codeViewVirtualRange = "code_view_virtual_range"
    case markdownPreview = "markdown_preview"
    case shikiHighlight = "shiki_highlight"
    case workerTask = "worker_task"
    case telemetryBatch = "telemetry_batch"
    case telemetryIngest = "telemetry_ingest"
    case telemetryDrop = "telemetry_drop"
    case unknown
}
