enum BridgeTelemetryDropReason: String, CaseIterable, Codable, Equatable, Sendable {
    case decodingFailed = "decoding_failed"
    case disabledScope = "disabled_scope"
    case encodedBatchTooLarge = "encoded_batch_too_large"
    case invalidDuration = "invalid_duration"
    case invalidTraceContext = "invalid_trace_context"
    case hostPortMessageInvalid = "host_port_message_invalid"
    case missingPushNonce = "missing_push_nonce"
    case pushDecodeFailed = "push_decode_failed"
    case pushNonceMismatch = "push_nonce_mismatch"
    case queueSaturated = "queue_saturated"
    case stalePush = "stale_push"
    case tooManySamples = "too_many_samples"
    case unsafeAttribute = "unsafe_attribute"
    case unsafeEventName = "unsafe_event_name"
    case unsupportedSchemaVersion = "unsupported_schema_version"
}
