export const bridgeViteOptimizedDependencies = [
	'@base-ui/react/combobox',
	'@pierre/diffs/worker',
	'@shikijs/markdown-exit',
	'markdown-exit',
	'react-dom/client',
	'shiki/core',
	'shiki/engine/javascript',
	'shiki/langs/css.mjs',
	'shiki/langs/diff.mjs',
	'shiki/langs/html.mjs',
	'shiki/langs/javascript.mjs',
	'shiki/langs/json.mjs',
	'shiki/langs/jsonc.mjs',
	'shiki/langs/md.mjs',
	'shiki/langs/shellscript.mjs',
	'shiki/langs/swift.mjs',
	'shiki/langs/tsx.mjs',
	'shiki/langs/typescript.mjs',
	'shiki/langs/yaml.mjs',
	'shiki/themes/github-dark.mjs',
	'zustand/vanilla',
] as const;
