import Foundation

extension BridgeTelemetryBatchValidator {
    static let requiredStringAttributeKeys: Set<String> = [
        "agentstudio.bridge.phase",
        "agentstudio.bridge.plane",
        "agentstudio.bridge.priority",
        "agentstudio.bridge.slice",
        "agentstudio.bridge.transport",
    ]

    static let allowedEventNames: Set<String> = [
        "performance.bridge.swift.active_viewer_mode_signal_rejected",
        "performance.bridge.swift.active_viewer_mode_suppression_catch_up",
        "performance.bridge.web.code_view_item_materialize",
        "performance.bridge.web.content_fetch",
        "performance.bridge.web.first_render",
        "performance.bridge.web.file_open_ready",
        "performance.bridge.web.intake_apply",
        "performance.bridge.web.intake_frame",
        "performance.bridge.web.push_apply",
        "performance.bridge.web.projection_input_build",
        "performance.bridge.web.projection_store_apply",
        "performance.bridge.web.projection_total",
        "performance.bridge.web.review_content_demand",
        "performance.bridge.web.review_ready",
        "performance.bridge.web.review_metadata_apply",
        "performance.bridge.web.selection_commit",
        "performance.bridge.web.selected_content_dropped",
        "performance.bridge.web.selected_content_painted",
        "performance.bridge.web.selected_content_ready",
        "performance.bridge.web.rpc_send",
        "performance.bridge.web.telemetry_drop",
        "performance.bridge.web.visible_demand_settled",
        "performance.bridge.web.worktree_file_intake_reject",
        "performance.bridge.markdown.render_queue",
        "performance.bridge.markdown.render",
        "performance.bridge.markdown.fallback",
        "performance.bridge.trees.projection_build",
        "performance.bridge.trees.prepare_input",
        "performance.bridge.trees.scroll_visible_demand",
        "performance.bridge.trees.mode_switch",
        "performance.bridge.trees.search_filter",
        "performance.bridge.viewer.content_queue",
        "performance.bridge.viewer.content_cache",
        "performance.bridge.viewer.time_to_first_interaction",
        "performance.bridge.pierre.item_update",
        "performance.bridge.pierre.scroll_target",
        "performance.bridge.pierre.virtualized_range",
        "performance.bridge.shiki.highlight",
        "performance.bridge.worker.task",
    ]

    static let allowedStringValuesByAttributeKey: [String: Set<String>] = [
        "agentstudio.bridge.active_source.protocol": [
            "none",
            "review",
            "worktree-file",
        ],
        "agentstudio.bridge.active_viewer.mode": [
            "file",
            "review",
        ],
        "agentstudio.bridge.active_viewer.signal_rejection_reason": [
            "session_reset",
            "stale_generation",
            "stale_sequence",
        ],
        "agentstudio.bridge.cache.result": [
            "cache_hit",
            "provider_load",
            "in_flight_coalesced",
            "rejected",
        ],
        "agentstudio.bridge.content.correlation_mode": [
            "summary",
            "traceparent",
        ],
        "agentstudio.bridge.content.role": [
            "base",
            "head",
            "diff",
            "file",
            "unknown",
        ],
        "agentstudio.bridge.content.interest": [
            "background",
            "selected",
            "unspecified",
            "visible",
            "nearby",
            "speculative",
        ],
        "agentstudio.bridge.demand.lane": [
            "active",
            "foreground",
            "idle",
            "nearby",
            "speculative",
            "visible",
        ],
        "agentstudio.bridge.demand.disposition": [
            "active-preloaded",
            "cache-hit",
            "cold-loaded",
            "idle-preloaded",
            "nearby-preloaded",
            "none",
            "published",
            "refreshed",
            "speculative-preloaded",
            "visible-preloaded",
        ],
        "agentstudio.bridge.drop_reason": [
            "contenthash_change",
            "generation_rotation",
            "revision_churn",
        ],
        "agentstudio.bridge.file_size_bucket": [
            "empty",
            "small",
            "medium",
            "large",
            "huge",
            "unknown",
        ],
        "agentstudio.bridge.content.priority": [
            "background",
            "nearby",
            "prefetch",
            "selected",
            "speculative",
            "visible",
        ],
        "agentstudio.bridge.content_bytes_bucket": [
            "empty",
            "small",
            "medium",
            "large",
            "huge",
            "unknown",
        ],
        "agentstudio.bridge.diff_row_count_bucket": [
            "small",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.fixture_class": [
            "smoke",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.generation.relation": [
            "current",
            "stale",
            "unknown",
        ],
        "agentstudio.bridge.generation_relation": [
            "current",
            "stale",
            "unknown",
        ],
        "agentstudio.bridge.intake.frame_kind": [
            "review.invalidate",
            "review.metadataDelta",
            "review.metadataSnapshot",
            "review.metadataWindow",
            "review.reset",
            "unknown",
        ],
        "agentstudio.bridge.phase": [
            "accepted",
            "active_viewer_mode_suppression_catch_up",
            "active_viewer_mode_signal_rejected",
            "apply",
            "content_register",
            "delta_build",
            "dispatch",
            "dropped",
            "error",
            "file_open_ready",
            "fetch",
            "package_apply",
            "package_build",
            "render",
            "send",
            "success",
            "transport",
            "content_queue",
            "content_cache",
            "code_view_item_materialize",
            "highlight",
            "intake",
            "item_update",
            "markdown_decision",
            "markdown_queue",
            "markdown_render",
            "demand_queue_wait",
            "metadata_full_manifest_complete",
            "metadata_open_to_first_window",
            "metadata_scheduler_job_execution",
            "metadata_scheduler_overflow_drop",
            "metadata_scheduler_stale_drop",
            "mode_switch",
            "prepare_input",
            "projection_input_build",
            "projection_store_apply",
            "projection_total",
            "projection_build",
            "review_content_demand",
            "review_ready",
            "review_metadata_apply",
            "scroll_visible_demand",
            "scroll_target",
            "search_filter",
            "selection_commit",
            "selected_content_dropped",
            "selected_content_painted",
            "selected_content_ready",
            "time_to_first_interaction",
            "visible_demand_settled",
            "virtualized_range",
            "worktree_file_frame_apply",
            "worktree_file_projection",
            "worker_task",
        ],
        "agentstudio.bridge.plane": Set(
            BridgeTelemetryPlane.allCases.map(\.rawValue)
        ),
        "agentstudio.bridge.priority": Set(
            BridgeTelemetryPriority.allCases.map(\.rawValue)
        ),
        "agentstudio.bridge.rpc.method_class": [
            "other",
            "review",
            "telemetry",
        ],
        "agentstudio.bridge.item_count_bucket": [
            "empty",
            "small",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.item_update.kind": [
            "add",
            "hydrate",
            "replace",
        ],
        "agentstudio.bridge.language_class": [
            "config",
            "markdown",
            "other",
            "swift",
            "text",
            "typescript",
        ],
        "agentstudio.bridge.markdown.fallback_reason": [
            "binaryContent",
            "contentPending",
            "contentUnavailable",
            "diffPatchResource",
            "invalidResourceUrl",
            "largeContent",
            "missingSelectedItem",
            "noSelectedItem",
            "notMarkdown",
            "twoSidedDiff",
            "workerUnavailable",
        ],
        "agentstudio.bridge.projection.kind": [
            "all_files",
            "changed_files",
            "current_change_set",
            "custom",
            "docs_and_plans",
            "guided_review",
            "normal_review",
            "plans_and_specs",
            "source",
            "tests",
        ],
        "agentstudio.bridge.protocol": [
            "review",
            "worktree-file",
        ],
        "agentstudio.bridge.query_class": [
            "empty",
            "extension",
            "path",
            "symbol",
        ],
        "agentstudio.bridge.queue.depth_bucket": [
            "empty",
            "small",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.result": [
            "added",
            "deferred",
            "dropped",
            "error",
            "failed",
            "failure",
            "fallback",
            "queued",
            "stale",
            "success",
            "unchanged",
            "updated",
        ],
        "agentstudio.bridge.result_reason": [
            "aborted",
            "byte_budget_exceeded",
            "carrier_nonce_mismatch",
            "closed",
            "concurrency_exceeded",
            "content_unavailable",
            "descriptor_missing",
            "descriptor_rejected",
            "duplicate_sequence",
            "frame_decode_failed",
            "frame_too_large",
            "generation_mismatch",
            "host_port_message_invalid",
            "intake_error",
            "load_failed",
            "load_threw",
            "metadata_carry_forward_verification",
            "missing_carrier_nonce",
            "no_demand",
            "none",
            "preview_only",
            "receiver_rejected_frame",
            "reset_required",
            "sequence_gap",
            "snapshot_descriptor_mismatch",
            "snapshot_materializer_rejected",
            "snapshot_package_parse_failed",
            "source_reset",
            "stale_completion",
            "stale_sequence",
            "stream_mismatch",
        ],
        "agentstudio.bridge.scroll_target.kind": [
            "item",
            "line",
            "position",
            "range",
        ],
        "agentstudio.bridge.slice": Set(
            BridgeTelemetrySlice.allCases.map(\.rawValue)
        ),
        "agentstudio.bridge.telemetry.drop_reason": Set(
            BridgeTelemetryDropReason.allCases.map(\.rawValue)
        ),
        "agentstudio.bridge.telemetry.first_rejected_event": allowedEventNames.union([
            unknownRejectedEventName
        ]),
        "agentstudio.bridge.test.scenario": [
            "package_apply_content_fetch_v1"
        ],
        "agentstudio.startup_diagnostic.bridge.file_view.expected_bootstrap.protocol": [
            "review",
            "worktree-file",
        ],
        "agentstudio.startup_diagnostic.bridge.file_view.bootstrap.protocol": [
            "review",
            "worktree-file",
        ],
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.last_frame_kind": [
            "none",
            "worktree.reset",
            "worktree.snapshot",
            "worktree.treeWindow",
        ],
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.last_reason": [
            "drop_frame_too_large",
            "drop_identity_mismatch",
            "drop_missing_push_nonce",
            "drop_nonce_mismatch",
            "drop_parse_failed",
            "frame_published",
            "handshake_received",
            "listener_installed",
            "none",
            "open_accepted",
            "replay_requested",
            "snapshot_resolved",
        ],
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.last_receiver_reason": [
            "closed",
            "duplicate_sequence",
            "generation_mismatch",
            "none",
            "reset_required",
            "sequence_gap",
            "stale_sequence",
            "stream_mismatch",
        ],
        "agentstudio.bridge.transport": [
            "content",
            "intake",
            "push",
            "rpc",
            "swift",
            "worker",
        ],
        "agentstudio.bridge.tree_path_count_bucket": [
            "empty",
            "small",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.visible_row_bucket": [
            "empty",
            "small",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.viewer": [
            "file",
            "review",
        ],
        "agentstudio.bridge.viewer.ttfi_variant": [
            "cold",
            "warm",
        ],
        "agentstudio.bridge.worker.lane": [
            "none",
            "markdown",
            "pierre",
            "projection",
        ],
        "agentstudio.bridge.worker.task_kind": [
            "highlight",
            "markdown_render",
            "pool_init",
            "projection",
        ],
    ]

    static let allowedNumericAttributeKeys: Set<String> = [
        "agentstudio.bridge.batch.sample_count",
        "agentstudio.bridge.active_viewer.signal_rejected.count",
        "agentstudio.bridge.content.byte_count",
        "agentstudio.bridge.content.byte_length",
        "agentstudio.bridge.content.byte_size_bucket",
        "agentstudio.bridge.content.body_registry_commit_ms",
        "agentstudio.bridge.content.chunk_byte_count",
        "agentstudio.bridge.content.chunk_count",
        "agentstudio.bridge.content.estimated_bytes",
        "agentstudio.bridge.content.first_chunk_wait_ms",
        "agentstudio.bridge.content.line_count_bucket",
        "agentstudio.bridge.content.response_wait_ms",
        "agentstudio.bridge.content.resource_count",
        "agentstudio.bridge.content.stream_read_ms",
        "agentstudio.bridge.content.total_bytes_read",
        "agentstudio.bridge.demand.active.count",
        "agentstudio.bridge.demand.deferred.count",
        "agentstudio.bridge.demand.duration_ms",
        "agentstudio.bridge.demand.enqueue_accepted.count",
        "agentstudio.bridge.demand.enqueue_rejected.count",
        "agentstudio.bridge.demand.executor_in_flight_ms",
        "agentstudio.bridge.demand.executor_pending_wait_ms",
        "agentstudio.bridge.demand.failed.count",
        "agentstudio.bridge.demand.foreground.count",
        "agentstudio.bridge.demand.idle.count",
        "agentstudio.bridge.demand.intent.count",
        "agentstudio.bridge.demand.loaded.count",
        "agentstudio.bridge.demand.nearby.count",
        "agentstudio.bridge.demand.request.sequence",
        "agentstudio.bridge.demand.scheduler_queue_wait_ms",
        "agentstudio.bridge.demand.speculative.count",
        "agentstudio.bridge.demand.visible.count",
        "agentstudio.bridge.generation",
        "agentstudio.bridge.intake.generation",
        "agentstudio.bridge.intake.sequence",
        "agentstudio.bridge.markdown.input_bytes",
        "agentstudio.bridge.markdown.output_bytes",
        "agentstudio.bridge.mode_gate.catch_up.count",
        "agentstudio.bridge.mode_gate.suppressed.count",
        "agentstudio.bridge.review.item_count",
        "agentstudio.bridge.review.metadata_carry_forward.unverified_keep.count",
        "agentstudio.bridge.review.metadata_carry_forward.verified_drop.count",
        "agentstudio.bridge.review.metadata_carry_forward.verified_keep.count",
        "agentstudio.bridge.source.generation",
        "agentstudio.bridge.selected_content.click_to_paint_ms",
        "agentstudio.bridge.selected_content.frame_wait_ms",
        "agentstudio.bridge.selected_content.materialize_ms",
        "agentstudio.bridge.telemetry.dropped_count",
        "agentstudio.bridge.visible_item.count",
        "agentstudio.bridge.worktree_file.tree.current_row.count",
        "agentstudio.bridge.worktree_file.tree.descriptor.count",
        "agentstudio.bridge.worktree_file.tree.incoming_frame.count",
        "agentstudio.bridge.worktree_file.receiver.generation",
        "agentstudio.bridge.worktree_file.tree.window.row.count",
        "agentstudio.startup_diagnostic.bridge.file_view.descriptor_request_command.count",
        "agentstudio.startup_diagnostic.bridge.file_view.metadata_file_row.count",
        "agentstudio.startup_diagnostic.bridge.file_view.metadata_tree_row.count",
        "agentstudio.startup_diagnostic.bridge.file_view.native_probe.last_sequence",
    ]

    static let allowedBooleanAttributeKeys: Set<String> = [
        "agentstudio.bridge.cache_hit",
        "agentstudio.bridge.content.binary",
        "agentstudio.bridge.content.stale",
        "agentstudio.bridge.header_missing",
        "agentstudio.bridge.header_supported",
        "agentstudio.bridge.reopen_signaled",
        "agentstudio.bridge.selected",
        "agentstudio.bridge.stream_id_matches",
    ]
}
