import Foundation

extension BridgeTelemetryBatchValidator {
    static let requiredStringAttributeKeys: Set<String> = [
        "agentstudio.bridge.phase",
        "agentstudio.bridge.plane",
        "agentstudio.bridge.priority",
        "agentstudio.bridge.slice",
        "agentstudio.bridge.transport",
    ]

    static let allowedEventNames: Set<String> = [
        "performance.bridge.web.content_fetch",
        "performance.bridge.web.first_render",
        "performance.bridge.web.intake_frame",
        "performance.bridge.web.package_apply",
        "performance.bridge.web.rpc_send",
        "performance.bridge.web.telemetry_drop",
        "performance.bridge.markdown.render_queue",
        "performance.bridge.markdown.render",
        "performance.bridge.markdown.fallback",
        "performance.bridge.trees.projection_build",
        "performance.bridge.trees.prepare_input",
        "performance.bridge.trees.mode_switch",
        "performance.bridge.trees.search_filter",
        "performance.bridge.viewer.content_queue",
        "performance.bridge.viewer.content_cache",
        "performance.bridge.pierre.item_update",
        "performance.bridge.pierre.scroll_target",
        "performance.bridge.pierre.virtualized_range",
        "performance.bridge.shiki.highlight",
        "performance.bridge.worker.task",
    ]

    static let allowedStringValuesByAttributeKey: [String: Set<String>] = [
        "agentstudio.bridge.cache.result": [
            "cache_hit",
            "provider_load",
            "in_flight_coalesced",
            "rejected",
        ],
        "agentstudio.bridge.content.correlation_mode": [
            "summary",
            "traceparent",
        ],
        "agentstudio.bridge.content.role": [
            "base",
            "head",
            "diff",
            "file",
            "unknown",
        ],
        "agentstudio.bridge.content.interest": [
            "selected",
            "visible",
            "nearby",
            "speculative",
        ],
        "agentstudio.bridge.content.priority": [
            "nearby",
            "prefetch",
            "selected",
            "speculative",
            "visible",
        ],
        "agentstudio.bridge.content_bytes_bucket": [
            "empty",
            "small",
            "medium",
            "large",
            "huge",
            "unknown",
        ],
        "agentstudio.bridge.diff_row_count_bucket": [
            "small",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.fixture_class": [
            "smoke",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.generation.relation": [
            "current",
            "stale",
            "unknown",
        ],
        "agentstudio.bridge.intake.frame_kind": [
            "review.delta",
            "review.invalidate",
            "review.reset",
            "review.snapshot",
            "unknown",
        ],
        "agentstudio.bridge.phase": [
            "accepted",
            "apply",
            "content_register",
            "delta_build",
            "dispatch",
            "dropped",
            "error",
            "fetch",
            "package_apply",
            "package_build",
            "render",
            "send",
            "success",
            "transport",
            "content_queue",
            "content_cache",
            "highlight",
            "intake",
            "item_update",
            "markdown_decision",
            "markdown_queue",
            "markdown_render",
            "mode_switch",
            "prepare_input",
            "projection_build",
            "scroll_target",
            "search_filter",
            "virtualized_range",
            "worker_task",
        ],
        "agentstudio.bridge.plane": Set(
            BridgeTelemetryPlane.allCases.map(\.rawValue)
        ),
        "agentstudio.bridge.priority": Set(
            BridgeTelemetryPriority.allCases.map(\.rawValue)
        ),
        "agentstudio.bridge.rpc.method_class": [
            "other",
            "review",
            "telemetry",
        ],
        "agentstudio.bridge.item_count_bucket": [
            "empty",
            "small",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.item_update.kind": [
            "add",
            "hydrate",
            "replace",
        ],
        "agentstudio.bridge.language_class": [
            "config",
            "markdown",
            "other",
            "swift",
            "text",
            "typescript",
        ],
        "agentstudio.bridge.markdown.fallback_reason": [
            "binaryContent",
            "contentPending",
            "contentUnavailable",
            "diffPatchResource",
            "invalidResourceUrl",
            "largeContent",
            "missingSelectedItem",
            "noSelectedItem",
            "notMarkdown",
            "twoSidedDiff",
            "workerUnavailable",
        ],
        "agentstudio.bridge.projection.kind": [
            "all_files",
            "changed_files",
            "current_change_set",
            "custom",
            "docs_and_plans",
            "guided_review",
            "normal_review",
            "plans_and_specs",
            "source",
            "tests",
        ],
        "agentstudio.bridge.query_class": [
            "empty",
            "extension",
            "path",
            "symbol",
        ],
        "agentstudio.bridge.queue.depth_bucket": [
            "empty",
            "small",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.result": [
            "deferred",
            "dropped",
            "error",
            "failed",
            "failure",
            "fallback",
            "queued",
            "stale",
            "success",
        ],
        "agentstudio.bridge.result_reason": [
            "aborted",
            "byte_budget_exceeded",
            "closed",
            "concurrency_exceeded",
            "descriptor_missing",
            "duplicate_sequence",
            "frame_decode_failed",
            "frame_too_large",
            "generation_mismatch",
            "load_failed",
            "load_threw",
            "missing_carrier_nonce",
            "none",
            "receiver_rejected_frame",
            "reset_required",
            "sequence_gap",
            "stale_completion",
            "stale_sequence",
            "stream_mismatch",
        ],
        "agentstudio.bridge.scroll_target.kind": [
            "item",
            "line",
            "position",
            "range",
        ],
        "agentstudio.bridge.slice": Set(
            BridgeTelemetrySlice.allCases.map(\.rawValue)
        ),
        "agentstudio.bridge.telemetry.drop_reason": Set(
            BridgeTelemetryDropReason.allCases.map(\.rawValue)
        ),
        "agentstudio.bridge.test.scenario": [
            "package_apply_content_fetch_v1"
        ],
        "agentstudio.bridge.transport": [
            "content",
            "intake",
            "push",
            "rpc",
            "swift",
            "worker",
        ],
        "agentstudio.bridge.tree_path_count_bucket": [
            "empty",
            "small",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.visible_row_bucket": [
            "empty",
            "small",
            "medium",
            "large",
            "huge",
        ],
        "agentstudio.bridge.worker.lane": [
            "none",
            "markdown",
            "pierre",
            "projection",
        ],
        "agentstudio.bridge.worker.task_kind": [
            "highlight",
            "markdown_render",
            "pool_init",
            "projection",
        ],
    ]

    static let allowedNumericAttributeKeys: Set<String> = [
        "agentstudio.bridge.batch.sample_count",
        "agentstudio.bridge.content.byte_size_bucket",
        "agentstudio.bridge.content.line_count_bucket",
        "agentstudio.bridge.intake.generation",
        "agentstudio.bridge.intake.sequence",
        "agentstudio.bridge.markdown.input_bytes",
        "agentstudio.bridge.markdown.output_bytes",
        "agentstudio.bridge.telemetry.dropped_count",
    ]

    static let allowedBooleanAttributeKeys: Set<String> = [
        "agentstudio.bridge.cache_hit",
        "agentstudio.bridge.content.binary",
        "agentstudio.bridge.content.stale",
        "agentstudio.bridge.header_missing",
        "agentstudio.bridge.header_supported",
    ]
}
