import Foundation

/// Generates JavaScript for a page-world test harness that captures bridge events.
///
/// The generated script runs as a `WKUserScript` in the **page world** at `.atDocumentEnd`.
/// It captures all three bridge data streams:
/// - State pushes (`__bridge_push` CustomEvents)
/// - Agent events (`__bridge_agent` CustomEvents)
/// - RPC responses (`__bridge_response` CustomEvents)
///
/// And provides helpers for the reverse direction:
/// - `sendCommand(method, params, commandId)` — dispatches `__bridge_command` with nonce
/// - `fetchResource(fileId)` — fetches `agentstudio://resource/file/{fileId}`
/// - `reportPushes()` / `reportCommands()` / `reportFetches()` — posts captures to testProbe
///
/// Follows the same `generateScript()` pattern as `BridgeBootstrap`.
enum BridgeTestHarness {

    // swiftlint:disable function_body_length
    /// Generate the page-world test harness JavaScript.
    ///
    /// The harness requests a handshake replay to capture the push nonce,
    /// then installs listeners for all bridge event types.
    ///
    /// - Returns: JavaScript source string to inject as WKUserScript in page world.
    static func generateScript() -> String {
        """
        // Bridge Test Harness — page-world probe for round-trip integration tests.
        // Generated by BridgeTestHarness.swift. DO NOT EDIT directly.
        (function() {
            'use strict';

            var pushNonce = null;

            // Capture storage
            var captures = {
                pushes: [],
                agentEvents: [],
                responses: [],
                fetches: []
            };

            // Listen for handshake to get push nonce
            document.addEventListener('__bridge_handshake', function(event) {
                if (event.detail && event.detail.pushNonce) {
                    pushNonce = event.detail.pushNonce;
                    // Report handshake received
                    window.webkit.messageHandlers.testProbe.postMessage(
                        JSON.stringify({ channel: 'handshake', data: { pushNonce: pushNonce } })
                    );
                }
            });

            // Request handshake replay (bootstrap fires at document start, we load at document end)
            document.dispatchEvent(new CustomEvent('__bridge_handshake_request'));

            // Capture state pushes
            document.addEventListener('__bridge_push', function(event) {
                var detail = event.detail || {};
                captures.pushes.push({
                    op: detail.op,
                    data: detail.data,
                    __revision: detail.__revision,
                    __epoch: detail.__epoch,
                    nonce: detail.nonce
                });
                // Auto-report each push for immediate assertion
                window.webkit.messageHandlers.testProbe.postMessage(
                    JSON.stringify({ channel: 'push', data: captures.pushes[captures.pushes.length - 1] })
                );
            });

            // Capture agent events
            document.addEventListener('__bridge_agent', function(event) {
                var detail = event.detail || {};
                captures.agentEvents.push({
                    events: detail.events,
                    nonce: detail.nonce
                });
                window.webkit.messageHandlers.testProbe.postMessage(
                    JSON.stringify({ channel: 'agent', data: captures.agentEvents[captures.agentEvents.length - 1] })
                );
            });

            // Capture RPC responses
            document.addEventListener('__bridge_response', function(event) {
                var detail = event.detail || {};
                captures.responses.push({
                    id: detail.id,
                    result: detail.result,
                    error: detail.error,
                    nonce: detail.nonce
                });
                window.webkit.messageHandlers.testProbe.postMessage(
                    JSON.stringify({ channel: 'response', data: captures.responses[captures.responses.length - 1] })
                );
            });

            // Expose command sender — reads bridge nonce from DOM attribute
            window.__testCaptures = {
                pushes: captures.pushes,
                agentEvents: captures.agentEvents,
                responses: captures.responses,
                fetches: captures.fetches,

                sendCommand: function(method, params, commandId) {
                    var bridgeNonce = document.documentElement.getAttribute('data-bridge-nonce');
                    if (!bridgeNonce) {
                        window.webkit.messageHandlers.testProbe.postMessage(
                            JSON.stringify({ channel: 'error', data: { message: 'No bridge nonce found on documentElement' } })
                        );
                        return;
                    }
                    var detail = {
                        jsonrpc: '2.0',
                        method: method,
                        params: params || {},
                        __nonce: bridgeNonce
                    };
                    if (commandId) {
                        detail.__commandId = commandId;
                    }
                    document.dispatchEvent(new CustomEvent('__bridge_command', { detail: detail }));
                },

                sendCommandWithId: function(id, method, params, commandId) {
                    var bridgeNonce = document.documentElement.getAttribute('data-bridge-nonce');
                    if (!bridgeNonce) {
                        window.webkit.messageHandlers.testProbe.postMessage(
                            JSON.stringify({ channel: 'error', data: { message: 'No bridge nonce found on documentElement' } })
                        );
                        return;
                    }
                    var detail = {
                        jsonrpc: '2.0',
                        id: id,
                        method: method,
                        params: params || {},
                        __nonce: bridgeNonce
                    };
                    if (commandId) {
                        detail.__commandId = commandId;
                    }
                    document.dispatchEvent(new CustomEvent('__bridge_command', { detail: detail }));
                },

                sendCommandWithBadNonce: function(method, params) {
                    var detail = {
                        jsonrpc: '2.0',
                        method: method,
                        params: params || {},
                        __nonce: 'invalid-nonce-for-testing'
                    };
                    document.dispatchEvent(new CustomEvent('__bridge_command', { detail: detail }));
                },

                fetchResource: function(fileId) {
                    return fetch('agentstudio://resource/file/' + encodeURIComponent(fileId))
                        .then(function(response) {
                            var entry = {
                                fileId: fileId,
                                status: response.status,
                                contentType: response.headers.get('Content-Type') || '',
                                ok: response.ok
                            };
                            return response.text().then(function(text) {
                                entry.body = text;
                                captures.fetches.push(entry);
                                window.webkit.messageHandlers.testProbe.postMessage(
                                    JSON.stringify({ channel: 'fetch', data: entry })
                                );
                                return entry;
                            });
                        })
                        .catch(function(err) {
                            var entry = {
                                fileId: fileId,
                                status: 0,
                                error: err.message || String(err),
                                ok: false
                            };
                            captures.fetches.push(entry);
                            window.webkit.messageHandlers.testProbe.postMessage(
                                JSON.stringify({ channel: 'fetch', data: entry })
                            );
                            return entry;
                        });
                }
            };

            // Signal that test harness is ready
            window.webkit.messageHandlers.testProbe.postMessage(
                JSON.stringify({ channel: 'ready', data: {} })
            );
        })();
        """
    }
    // swiftlint:enable function_body_length
}
