@testable import AgentStudio

struct HydratedBridgeSmokeRenderProofOptions {
    let expectedReviewItemCount: Int
    let reviewMetadataItemCount: Int
    let reviewMetadataTreeRowCount: Int
    let selectedContentLineCount: Int
    let pageErrorCount: Int
    let pageIssueLastKind: String
    let pageIssueLastClass: String
    let pageIssueDisallowedCount: Int
    let codeLineCount: Int
    let firstDiffContainerHeight: Int
    let firstDiffContainerPreTextLength: Int
    let codeViewInstanceFirstItemHeight: Int
    let codeViewRenderedItemCount: Int
    let codeViewRenderedItemType: String
    let codeViewRenderedItemVersion: Int
    let codeTextLength: Int
    let codeShadowTextLength: Int

    init(
        expectedReviewItemCount: Int,
        reviewMetadataItemCount: Int,
        reviewMetadataTreeRowCount: Int,
        selectedContentLineCount: Int,
        pageErrorCount: Int = 0,
        pageIssueLastKind: String = "none",
        pageIssueLastClass: String = "none",
        pageIssueDisallowedCount: Int = 0,
        codeLineCount: Int,
        firstDiffContainerHeight: Int,
        firstDiffContainerPreTextLength: Int,
        codeViewInstanceFirstItemHeight: Int,
        codeViewRenderedItemCount: Int,
        codeViewRenderedItemType: String,
        codeViewRenderedItemVersion: Int,
        codeTextLength: Int,
        codeShadowTextLength: Int
    ) {
        self.expectedReviewItemCount = expectedReviewItemCount
        self.reviewMetadataItemCount = reviewMetadataItemCount
        self.reviewMetadataTreeRowCount = reviewMetadataTreeRowCount
        self.selectedContentLineCount = selectedContentLineCount
        self.pageErrorCount = pageErrorCount
        self.pageIssueLastKind = pageIssueLastKind
        self.pageIssueLastClass = pageIssueLastClass
        self.pageIssueDisallowedCount = pageIssueDisallowedCount
        self.codeLineCount = codeLineCount
        self.firstDiffContainerHeight = firstDiffContainerHeight
        self.firstDiffContainerPreTextLength = firstDiffContainerPreTextLength
        self.codeViewInstanceFirstItemHeight = codeViewInstanceFirstItemHeight
        self.codeViewRenderedItemCount = codeViewRenderedItemCount
        self.codeViewRenderedItemType = codeViewRenderedItemType
        self.codeViewRenderedItemVersion = codeViewRenderedItemVersion
        self.codeTextLength = codeTextLength
        self.codeShadowTextLength = codeShadowTextLength
    }
}

// swiftlint:disable:next function_body_length
func makeHydratedBridgeSmokeRenderProof(
    _ options: HydratedBridgeSmokeRenderProofOptions
) -> BridgeReviewObservabilitySmokeRenderProof {
    BridgeReviewObservabilitySmokeRenderProof(
        expectedVisiblePaneCount: 1,
        expectedReviewItemCount: options.expectedReviewItemCount,
        hasReviewShell: true,
        reviewShellState: "ready",
        hasCodeViewPanel: true,
        hasSelectedItem: true,
        hasSelectedDisplayPath: true,
        selectedChangeKind: "modified",
        reviewMetadataItemCount: options.reviewMetadataItemCount,
        reviewMetadataTreeRowCount: options.reviewMetadataTreeRowCount,
        hasSelectedContentText: true,
        selectedContentState: "ready",
        selectedContentRoleCount: 2,
        selectedContentCacheKeyCount: 2,
        selectedContentRoles: "base,head",
        selectedContentCacheKeys: "base:cache-base,head:cache-head",
        selectedContentCharacterCount: 135,
        selectedContentLineCount: options.selectedContentLineCount,
        selectedMaterializedUpdateResult: "updated",
        selectedMaterializedItemType: "diff",
        selectedMaterializedItemVersion: 5,
        selectedMaterializedAdditionLineCount: 4,
        selectedMaterializedDeletionLineCount: 3,
        selectedMaterializedFileLineCount: 0,
        pageErrorCount: options.pageErrorCount,
        pageIssueLastKind: options.pageIssueLastKind,
        pageIssueLastClass: options.pageIssueLastClass,
        pageIssueDisallowedCount: options.pageIssueDisallowedCount,
        diffContainerCount: 1,
        codeLineCount: options.codeLineCount,
        codeViewPanelWidth: 2208,
        codeViewPanelHeight: 1081,
        firstDiffContainerWidth: 2208,
        firstDiffContainerHeight: options.firstDiffContainerHeight,
        codeViewScrollOwnerHeight: 1081,
        codeViewScrollOwnerScrollHeight: 1081,
        codeViewScrollOwnerChildCount: 1,
        codeViewScrollOwnerFirstChildTag: "diffs-container",
        codeViewInstanceHeight: 1081,
        codeViewInstanceScrollHeight: 152,
        codeViewInstanceItemCount: 1,
        codeViewInstanceWindowTop: 0,
        codeViewInstanceWindowBottom: 1081,
        codeViewInstanceFirstRenderedIndex: 0,
        codeViewInstanceLastRenderedIndex: 0,
        codeViewInstanceFirstItemHeight: options.codeViewInstanceFirstItemHeight,
        codeViewInstanceFirstItemTop: 0,
        codeViewRenderedItemCount: options.codeViewRenderedItemCount,
        codeViewRenderedItemElementHeight: 0,
        codeViewRenderedItemElementChildCount: 1,
        codeViewRenderedItemElementFirstChildTag: "diffs-container",
        codeViewRenderedItemType: options.codeViewRenderedItemType,
        codeViewRenderedItemVersion: options.codeViewRenderedItemVersion,
        firstDiffContainerShadowChildCount: 0,
        firstDiffContainerPreCount: 1,
        firstDiffContainerOffsetHeight: 0,
        firstDiffContainerScrollHeight: 0,
        firstDiffContainerPreHeight: 0,
        firstDiffContainerPreTextLength: options.firstDiffContainerPreTextLength,
        codeLineWithDataLineCount: 0,
        firstDiffContainerDisplay: "block",
        workerPoolState: "ready",
        workerPoolManagerState: "initialized",
        workerPoolWorkersFailed: false,
        workerPoolTotalWorkers: 2,
        workerPoolBusyWorkers: 0,
        workerPoolQueuedTasks: 0,
        workerPoolActiveTasks: 0,
        workerPoolFileCacheSize: 0,
        workerPoolDiffCacheSize: 1,
        workerPoolInitializationProbeStage: "highlighter-loaded",
        workerPoolInitializationProbeThemeCount: 2,
        workerPoolInitializationProbeLanguageCount: 7,
        workerPoolInitializationProbeFailureReason: "",
        workerDiagnosticBootstrapState: "started",
        workerDiagnosticInitializeRequestIdState: "present",
        workerDiagnosticLastMessageType: "success",
        workerDiagnosticLastRequestType: "initialize",
        workerDiagnosticLastSuccessMatchesInitializeRequest: "yes",
        workerDiagnosticLastSuccessIdState: "present",
        workerDiagnosticLastSuccessIdPrefix: "req",
        workerDiagnosticLastSuccessRequestType: "diff",
        workerDiagnosticSuccessCount: 2,
        workerDiagnosticInitializeSuccessCount: 1,
        workerDiagnosticDiffSuccessCount: 1,
        workerDiagnosticFileSuccessCount: 0,
        workerDiagnosticForwardedMessageCount: 2,
        workerDiagnosticLastForwardResult: "ok",
        workerDiagnosticErrorCount: 0,
        workerDiagnosticLastErrorKind: "none",
        codeTextLength: options.codeTextLength,
        codeShadowTextLength: options.codeShadowTextLength,
        bridgeCommandCount: 2,
        reviewIntakeReadyCommandCount: 1,
        bridgeResponseCount: 1,
        intakeFrameCount: 2,
        reviewIntakeSnapshotFrameCount: 1,
        reviewIntakeMetadataWindowFrameCount: 1,
        reviewIntakeLastFrameKind: "delta",
        reviewIntakeLastStreamIdMatches: true,
        modifiedClickTargetPath: "Sources/App/Modified.swift",
        modifiedClickSelectedPath: "Sources/App/Modified.swift",
        modifiedClickSelectedChangeKind: "modified",
        modifiedClickSelectedContentState: "ready",
        modifiedClickSelectedContentRoles: "base,head",
        modifiedClickSelectedContentCacheKeys: "base:cache-base,head:cache-head",
        modifiedClickSelectedMaterializedItemType: "diff",
        modifiedClickSelectedMaterializedItemVersion: options.codeViewRenderedItemVersion,
        modifiedClickSelectedCharacterCount: 135
    )
}

// swiftlint:disable:next function_body_length
func makeFullyHydratedBridgeSmokeRenderProof() -> BridgeReviewObservabilitySmokeRenderProof {
    BridgeReviewObservabilitySmokeRenderProof(
        expectedVisiblePaneCount: 1,
        expectedReviewItemCount: 3,
        hasReviewShell: true,
        reviewShellState: "ready",
        hasCodeViewPanel: true,
        hasSelectedItem: true,
        hasSelectedDisplayPath: true,
        selectedChangeKind: "modified",
        reviewMetadataItemCount: 3,
        reviewMetadataTreeRowCount: 3,
        hasSelectedContentText: true,
        selectedContentState: "ready",
        selectedContentRoleCount: 2,
        selectedContentCacheKeyCount: 2,
        selectedContentRoles: "base,head",
        selectedContentCacheKeys: "base:cache-base,head:cache-head",
        selectedContentCharacterCount: 180,
        selectedContentLineCount: 12,
        selectedMaterializedUpdateResult: "updated",
        selectedMaterializedItemType: "diff",
        selectedMaterializedItemVersion: 3,
        selectedMaterializedAdditionLineCount: 4,
        selectedMaterializedDeletionLineCount: 2,
        selectedMaterializedFileLineCount: 0,
        paintedProbeAnchoredDeliveryEntryCount: 1,
        paintedProbeAnchoredDeliveryAnchorPresentCount: 1,
        paintedProbeAnchoredDeliverySelectedMatchCount: 1,
        paintedProbeAnchoredDeliveryTelemetryRecorderPresentCount: 1,
        paintedProbeAlreadyPaintedByHydrationCount: 1,
        paintedProbeScheduleEnteredCount: 2,
        paintedProbeEarlyReturnCount: 1,
        paintedProbeRafScheduledCount: 1,
        paintedProbeRafFiredCount: 1,
        paintedProbeGenerationSupersededCount: 0,
        paintedProbeSampleRecordedCount: 1,
        paintedProbeFlushCalledCount: 1,
        paintedProbeLastAnchoredDeliveryHadAnchor: true,
        paintedProbeLastAnchoredDeliverySelectedMatched: true,
        paintedProbeLastAnchoredDeliveryHadTelemetryRecorder: true,
        paintedProbeLastReason: "flush_called",
        paintedProbeLastScheduleEarlyReturnReason: "duplicate_selection_demand",
        pageErrorCount: 0,
        pageIssueLastKind: "none",
        pageIssueLastClass: "none",
        diffContainerCount: 1,
        codeLineCount: 4,
        codeViewPanelWidth: 900,
        codeViewPanelHeight: 700,
        firstDiffContainerWidth: 880,
        firstDiffContainerHeight: 600,
        codeViewScrollOwnerHeight: 700,
        codeViewScrollOwnerScrollHeight: 1200,
        codeViewScrollOwnerChildCount: 1,
        codeViewScrollOwnerFirstChildTag: "diffs-container",
        codeViewInstanceHeight: 700,
        codeViewInstanceScrollHeight: 1200,
        codeViewInstanceItemCount: 1,
        codeViewInstanceWindowTop: 0,
        codeViewInstanceWindowBottom: 700,
        codeViewInstanceFirstRenderedIndex: 0,
        codeViewInstanceLastRenderedIndex: 0,
        codeViewInstanceFirstItemHeight: 600,
        codeViewInstanceFirstItemTop: 0,
        codeViewRenderedItemCount: 1,
        codeViewRenderedItemElementHeight: 600,
        codeViewRenderedItemElementChildCount: 1,
        codeViewRenderedItemElementFirstChildTag: "diffs-container",
        codeViewRenderedItemType: "diff",
        codeViewRenderedItemVersion: 3,
        firstDiffContainerShadowChildCount: 3,
        firstDiffContainerPreCount: 1,
        firstDiffContainerOffsetHeight: 600,
        firstDiffContainerScrollHeight: 1200,
        firstDiffContainerPreHeight: 560,
        firstDiffContainerPreTextLength: 88,
        codeLineWithDataLineCount: 4,
        firstDiffContainerDisplay: "block",
        workerPoolState: "ready",
        workerPoolManagerState: "initialized",
        workerPoolWorkersFailed: false,
        workerPoolTotalWorkers: 2,
        workerPoolBusyWorkers: 0,
        workerPoolQueuedTasks: 0,
        workerPoolActiveTasks: 0,
        workerPoolFileCacheSize: 1,
        workerPoolDiffCacheSize: 1,
        workerPoolInitializationProbeStage: "idle",
        workerPoolInitializationProbeThemeCount: 0,
        workerPoolInitializationProbeLanguageCount: 0,
        workerPoolInitializationProbeFailureReason: "",
        workerDiagnosticBootstrapState: "started",
        workerDiagnosticInitializeRequestIdState: "present",
        workerDiagnosticLastMessageType: "success",
        workerDiagnosticLastRequestType: "initialize",
        workerDiagnosticLastSuccessMatchesInitializeRequest: "yes",
        workerDiagnosticLastSuccessIdState: "present",
        workerDiagnosticLastSuccessIdPrefix: "req",
        workerDiagnosticLastSuccessRequestType: "diff",
        workerDiagnosticSuccessCount: 2,
        workerDiagnosticInitializeSuccessCount: 1,
        workerDiagnosticDiffSuccessCount: 1,
        workerDiagnosticFileSuccessCount: 0,
        workerDiagnosticForwardedMessageCount: 2,
        workerDiagnosticLastForwardResult: "ok",
        workerDiagnosticErrorCount: 0,
        workerDiagnosticLastErrorKind: "none",
        codeTextLength: 120,
        codeShadowTextLength: 88,
        modifiedClickTargetPath: "Sources/App/Modified.swift",
        modifiedClickSelectedPath: "Sources/App/Modified.swift",
        modifiedClickSelectedChangeKind: "modified",
        modifiedClickSelectedContentState: "ready",
        modifiedClickSelectedContentRoles: "base,head",
        modifiedClickSelectedContentCacheKeys: "base:cache-base,head:cache-head",
        modifiedClickSelectedMaterializedItemType: "diff",
        modifiedClickSelectedMaterializedItemVersion: 3,
        modifiedClickSelectedCharacterCount: 180
    )
}

// swiftlint:disable:next function_body_length
func makeBridgeSmokeRenderProofWithoutNativeReviewIntakeLineage() -> BridgeReviewObservabilitySmokeRenderProof {
    BridgeReviewObservabilitySmokeRenderProof(
        expectedVisiblePaneCount: 1,
        expectedReviewItemCount: 3,
        hasReviewShell: true,
        reviewShellState: "ready",
        hasCodeViewPanel: true,
        hasSelectedItem: true,
        hasSelectedDisplayPath: true,
        selectedChangeKind: "modified",
        reviewMetadataItemCount: 3,
        reviewMetadataTreeRowCount: 4,
        hasSelectedContentText: true,
        selectedContentState: "ready",
        selectedContentRoleCount: 2,
        selectedContentCacheKeyCount: 2,
        selectedContentRoles: "base,head",
        selectedContentCacheKeys: "base:cache-base,head:cache-head",
        selectedContentCharacterCount: 135,
        selectedContentLineCount: 7,
        selectedMaterializedUpdateResult: "updated",
        selectedMaterializedItemType: "diff",
        selectedMaterializedItemVersion: 5,
        selectedMaterializedAdditionLineCount: 4,
        selectedMaterializedDeletionLineCount: 3,
        selectedMaterializedFileLineCount: 0,
        pageErrorCount: 0,
        pageIssueLastKind: "none",
        pageIssueLastClass: "none",
        pageIssueDisallowedCount: 0,
        diffContainerCount: 1,
        codeLineCount: 0,
        codeViewPanelWidth: 2208,
        codeViewPanelHeight: 1081,
        firstDiffContainerWidth: 2208,
        firstDiffContainerHeight: 0,
        codeViewScrollOwnerHeight: 1081,
        codeViewScrollOwnerScrollHeight: 1081,
        codeViewScrollOwnerChildCount: 1,
        codeViewScrollOwnerFirstChildTag: "diffs-container",
        codeViewInstanceHeight: 1081,
        codeViewInstanceScrollHeight: 152,
        codeViewInstanceItemCount: 1,
        codeViewInstanceWindowTop: 0,
        codeViewInstanceWindowBottom: 1081,
        codeViewInstanceFirstRenderedIndex: 0,
        codeViewInstanceLastRenderedIndex: 0,
        codeViewInstanceFirstItemHeight: 152,
        codeViewInstanceFirstItemTop: 0,
        codeViewRenderedItemCount: 1,
        codeViewRenderedItemElementHeight: 0,
        codeViewRenderedItemElementChildCount: 1,
        codeViewRenderedItemElementFirstChildTag: "diffs-container",
        codeViewRenderedItemType: "diff",
        codeViewRenderedItemVersion: 5,
        firstDiffContainerShadowChildCount: 0,
        firstDiffContainerPreCount: 1,
        firstDiffContainerOffsetHeight: 0,
        firstDiffContainerScrollHeight: 0,
        firstDiffContainerPreHeight: 0,
        firstDiffContainerPreTextLength: 0,
        codeLineWithDataLineCount: 0,
        firstDiffContainerDisplay: "block",
        workerPoolState: "ready",
        workerPoolManagerState: "initialized",
        workerPoolWorkersFailed: false,
        workerPoolTotalWorkers: 2,
        workerPoolBusyWorkers: 0,
        workerPoolQueuedTasks: 0,
        workerPoolActiveTasks: 0,
        workerPoolFileCacheSize: 0,
        workerPoolDiffCacheSize: 1,
        workerPoolInitializationProbeStage: "highlighter-loaded",
        workerPoolInitializationProbeThemeCount: 2,
        workerPoolInitializationProbeLanguageCount: 7,
        workerPoolInitializationProbeFailureReason: "",
        workerDiagnosticBootstrapState: "started",
        workerDiagnosticInitializeRequestIdState: "present",
        workerDiagnosticLastMessageType: "success",
        workerDiagnosticLastRequestType: "initialize",
        workerDiagnosticLastSuccessMatchesInitializeRequest: "yes",
        workerDiagnosticLastSuccessIdState: "present",
        workerDiagnosticLastSuccessIdPrefix: "req",
        workerDiagnosticLastSuccessRequestType: "diff",
        workerDiagnosticSuccessCount: 2,
        workerDiagnosticInitializeSuccessCount: 1,
        workerDiagnosticDiffSuccessCount: 1,
        workerDiagnosticFileSuccessCount: 0,
        workerDiagnosticForwardedMessageCount: 2,
        workerDiagnosticLastForwardResult: "ok",
        workerDiagnosticErrorCount: 0,
        workerDiagnosticLastErrorKind: "none",
        codeTextLength: 1471,
        codeShadowTextLength: 1466,
        bridgeCommandCount: 0,
        reviewIntakeReadyCommandCount: 0,
        bridgeResponseCount: 0,
        intakeFrameCount: 0,
        reviewIntakeSnapshotFrameCount: 0,
        reviewIntakeMetadataWindowFrameCount: 0,
        reviewIntakeLastFrameKind: "none",
        reviewIntakeLastStreamIdMatches: false,
        modifiedClickTargetPath: "Sources/App/Modified.swift",
        modifiedClickSelectedPath: "Sources/App/Modified.swift",
        modifiedClickSelectedChangeKind: "modified",
        modifiedClickSelectedContentState: "ready",
        modifiedClickSelectedContentRoles: "base,head",
        modifiedClickSelectedContentCacheKeys: "base:cache-base,head:cache-head",
        modifiedClickSelectedMaterializedItemType: "diff",
        modifiedClickSelectedMaterializedItemVersion: 5,
        modifiedClickSelectedCharacterCount: 135
    )
}
