import Foundation

/// Generates the JavaScript bootstrap script injected into the bridge content world.
///
/// This script runs at document start in the bridge world (not page world).
/// It handles bootstrap readiness plus product and telemetry session requests.
enum BridgeBootstrap {

    /// Generate the bootstrap JavaScript for a bridge pane.
    ///
    /// - Returns: JavaScript source string to inject as WKUserScript in bridge content world.
    static func generateScript(
        appProtocol: String? = nil,
        reviewPaneId: String? = nil,
        reviewStreamId: String? = nil,
        telemetryConfig: BridgeTelemetryBootstrapConfig? = nil
    ) -> String {
        let appProtocolJSON = encodedOptionalJSONString(appProtocol)
        let reviewPaneIdJSON = encodedOptionalJSONString(reviewPaneId)
        let reviewStreamIdJSON = encodedOptionalJSONString(reviewStreamId)
        let telemetryConfigJSON = encodedTelemetryConfigJSON(telemetryConfig)
        return """
            // Bridge Bootstrap — injected at document start in bridge content world.
            // DO NOT EDIT this output directly — generated by BridgeBootstrap.swift.
            (function() {
                'use strict';

                const APP_PROTOCOL = \(appProtocolJSON);
                const REVIEW_PANE_ID = \(reviewPaneIdJSON);
                const REVIEW_STREAM_ID = \(reviewStreamIdJSON);
                const TELEMETRY_CONFIG = \(telemetryConfigJSON);
                // Listen for bridge.ready from page world
                document.addEventListener('__bridge_ready', function(event) {
                    const requestId = event && event.detail && typeof event.detail.requestId === 'string'
                        ? event.detail.requestId
                        : null;
                    if (requestId === null || requestId.length === 0) {
                        console.warn('[BridgeBootstrap] Rejected bridge.ready: missing request id');
                        return;
                    }
                    window.webkit.messageHandlers.rpc.postMessage(
                        JSON.stringify({ jsonrpc: '2.0', id: requestId, method: 'bridge.ready', params: {} })
                    );
                });

                // Dispatch bootstrap context to the page world.
                document.dispatchEvent(new CustomEvent('__bridge_handshake', {
                    detail: { telemetryConfig: TELEMETRY_CONFIG }
                }));

                // Replay handshake for late page-world listeners (P1 fix).
                // The initial __bridge_handshake fires at document start, but the React
                // bundle typically loads later and misses it. Page world can dispatch
                // __bridge_handshake_request to receive replayed bootstrap context.
                document.addEventListener('__bridge_handshake_request', function() {
                    document.dispatchEvent(new CustomEvent('__bridge_handshake', {
                        detail: { telemetryConfig: TELEMETRY_CONFIG }
                    }));
                });
                document.addEventListener('__bridge_product_session_bootstrap_request', function(event) {
                    const detail = event && event.detail;
                    const requestId = detail && typeof detail.requestId === 'string'
                        ? detail.requestId
                        : null;
                    const reason = detail && (detail.reason === 'initial'
                        || detail.reason === 'workerReplacement')
                        ? detail.reason
                        : null;
                    if (requestId === null || requestId.length === 0 || reason === null) {
                        console.warn('[BridgeBootstrap] Rejected product bootstrap request');
                        return;
                    }
                    window.webkit.messageHandlers.rpc.postMessage(JSON.stringify({
                        jsonrpc: '2.0',
                        id: requestId,
                        method: 'bridge.productSession.bootstrap',
                        params: { reason: reason }
                    }));
                });
                document.addEventListener('__bridge_telemetry_session_bootstrap_request', function(event) {
                    const detail = event && event.detail;
                    const requestId = detail && typeof detail.requestId === 'string'
                        ? detail.requestId
                        : null;
                    const reason = detail && (detail.reason === 'initial'
                        || detail.reason === 'sidecarReplacement')
                        ? detail.reason
                        : null;
                    if (requestId === null || requestId.length === 0 || reason === null) {
                        console.warn('[BridgeBootstrap] Rejected telemetry bootstrap request');
                        return;
                    }
                    window.webkit.messageHandlers.rpc.postMessage(JSON.stringify({
                        jsonrpc: '2.0',
                        id: requestId,
                        method: 'bridge.telemetrySession.bootstrap',
                        params: { reason: reason }
                    }));
                });
                if (typeof REVIEW_PANE_ID === 'string' && typeof REVIEW_STREAM_ID === 'string') {
                    document.documentElement.setAttribute('data-bridge-review-pane-id', REVIEW_PANE_ID);
                    document.documentElement.setAttribute('data-bridge-review-stream-id', REVIEW_STREAM_ID);
                }
                if (typeof APP_PROTOCOL === 'string') {
                    document.documentElement.setAttribute('data-bridge-app-protocol', APP_PROTOCOL);
                }
            })();
            """
    }

    private static func encodedOptionalJSONString(_ value: String?) -> String {
        guard let value else {
            return "null"
        }
        return encodedJSONString(value)
    }

    private static func encodedJSONString(_ value: String) -> String {
        guard let data = try? JSONEncoder().encode(value),
            let json = String(data: data, encoding: .utf8)
        else {
            return "null"
        }
        return json
    }

    private static func encodedTelemetryConfigJSON(_ telemetryConfig: BridgeTelemetryBootstrapConfig?) -> String {
        guard let telemetryConfig else {
            return "null"
        }

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        guard let data = try? encoder.encode(telemetryConfig),
            let json = String(data: data, encoding: .utf8)
        else {
            return "null"
        }
        return json
    }
}
