import Foundation

/// Generates the JavaScript bootstrap script injected into the bridge content world.
///
/// This script runs at document start in the bridge world (not page world).
/// It installs `window.__bridgeInternal` with relay functions for state pushes,
/// listens for commands from page world with nonce validation, and handles the
/// bridge.ready handshake.
///
/// Implements handshake, nonce validation, and bootstrap injection for bridge runtime.
enum BridgeBootstrap {

    // swiftlint:disable function_body_length
    /// Generate the bootstrap JavaScript for a bridge pane.
    ///
    /// - Parameters:
    ///   - bridgeNonce: Nonce for validating commands from page world.
    ///     Page world must include this nonce in `__bridge_command` events.
    ///   - pushNonce: Nonce sent to page world in handshake for push event validation.
    ///     Page world uses this to verify incoming `__bridge_push` events.
    /// - Returns: JavaScript source string to inject as WKUserScript in bridge content world.
    static func generateScript(
        bridgeNonce: String,
        pushNonce: String,
        reviewPaneId: String? = nil,
        reviewStreamId: String? = nil,
        worktreeFileSourceSpec: BridgeWorktreeFileSurfaceSourceSpec? = nil,
        telemetryConfig: BridgeTelemetryBootstrapConfig? = nil
    ) -> String {
        let reviewPaneIdJSON = encodedOptionalJSONString(reviewPaneId)
        let reviewStreamIdJSON = encodedOptionalJSONString(reviewStreamId)
        let worktreeFileSourceSpecJSON = encodedWorktreeFileSourceSpecJSON(worktreeFileSourceSpec)
        let telemetryConfigJSON = encodedTelemetryConfigJSON(telemetryConfig)
        return """
            // Bridge Bootstrap — injected at document start in bridge content world.
            // DO NOT EDIT this output directly — generated by BridgeBootstrap.swift.
            (function() {
                'use strict';

                const BRIDGE_NONCE = '\(bridgeNonce)';
                const PUSH_NONCE = '\(pushNonce)';
                const REVIEW_PANE_ID = \(reviewPaneIdJSON);
                const REVIEW_STREAM_ID = \(reviewStreamIdJSON);
                const WORKTREE_FILE_SOURCE_SPEC = \(worktreeFileSourceSpecJSON);
                const TELEMETRY_CONFIG = \(telemetryConfigJSON);
                const PENDING_INTAKE_FRAME_JSON = [];
                const MAX_PENDING_INTAKE_FRAMES = 64;
                const PAGE_WORLD_ALLOWED_COMMAND_METHODS = new Set([
                    'bridge.intakeReady',
                    'review.markFileViewed',
                    'worktreeFileSurface.openSourceStream',
                    'system.bridgeTelemetry'
                ]);
                const HOST_PUSH_PORTS = new Set();
                const HOST_INTAKE_PORTS = new Set();

                function publishHostPushPort() {
                    const channel = new MessageChannel();
                    HOST_PUSH_PORTS.add(channel.port1);
                    channel.port1.start();
                    window.postMessage({
                        type: 'agentstudio.bridge.hostPushPort',
                        version: 1
                    }, '*', [channel.port2]);
                }

                function postHostEnvelopeJSON(envelopeJSON) {
                    for (const port of HOST_PUSH_PORTS) {
                        port.postMessage({
                            type: 'agentstudio.bridge.hostPushEnvelopeJSON',
                            version: 1,
                            json: envelopeJSON
                        });
                    }
                }

                function publishHostIntakePort() {
                    const channel = new MessageChannel();
                    HOST_INTAKE_PORTS.add(channel.port1);
                    channel.port1.start();
                    window.postMessage({
                        type: 'agentstudio.bridge.hostIntakePort',
                        version: 1
                    }, '*', [channel.port2]);
                }

                function postHostIntakeFrameJSON(frameJSON) {
                    for (const port of HOST_INTAKE_PORTS) {
                        port.postMessage({
                            type: 'agentstudio.bridge.hostIntakeFrameJSON',
                            version: 1,
                            json: frameJSON
                        });
                    }
                }

                function dispatchIntakeFrameJSON(frameJSON) {
                    if (PENDING_INTAKE_FRAME_JSON.length >= MAX_PENDING_INTAKE_FRAMES) {
                        PENDING_INTAKE_FRAME_JSON.shift();
                    }
                    PENDING_INTAKE_FRAME_JSON.push(frameJSON);
                    postHostIntakeFrameJSON(frameJSON);
                    document.dispatchEvent(new CustomEvent('__bridge_intake_json', {
                        detail: { json: frameJSON, nonce: PUSH_NONCE }
                    }));
                }

                // Install bridge internal API in bridge world only.
                // Page world cannot access this (content world isolation).
                window.__bridgeInternal = {
                    // Push state to page world via CustomEvent.
                    // Envelope metadata (__revision, __epoch) is lifted to detail level
                    // so receiver-side stale/epoch guards work without nested unwrapping.
                    merge: function(store, data, revision, epoch, slice, traceContext) {
                        document.dispatchEvent(new CustomEvent('__bridge_push', {
                            detail: {
                                op: 'merge',
                                store: store,
                                slice: slice,
                                data: data,
                                __revision: revision,
                                __epoch: epoch,
                                __traceContext: traceContext || null,
                                nonce: PUSH_NONCE
                            }
                        }));
                    },
                    replace: function(store, data, revision, epoch, slice, traceContext) {
                        document.dispatchEvent(new CustomEvent('__bridge_push', {
                            detail: {
                                op: 'replace',
                                store: store,
                                slice: slice,
                                data: data,
                                __revision: revision,
                                __epoch: epoch,
                                __traceContext: traceContext || null,
                                nonce: PUSH_NONCE
                            }
                        }));
                    },
                    applyEnvelope: function(envelope) {
                        const op = envelope.op || 'replace';
                        const revision = envelope.__revision;
                        const epoch = envelope.__epoch;
                        const slice = envelope.slice;
                        const traceContext = envelope.__traceContext || null;
                        const store = envelope.store;
                        const payload = envelope.payload !== undefined ? envelope.payload : envelope.data;
                        if (payload === undefined) {
                            console.warn('[BridgeInternal] applyEnvelope: payload is undefined, envelope dropped', JSON.stringify({op: op}));
                            return;
                        }
                        // Forward envelope as data with metadata lifted to detail level.
                        if (op === 'merge') {
                            this.merge(store, payload, revision, epoch, slice, traceContext);
                        } else {
                            this.replace(store, payload, revision, epoch, slice, traceContext);
                        }
                    },
                    applyEnvelopeJSON: function(envelopeJSON) {
                        postHostEnvelopeJSON(envelopeJSON);
                        document.dispatchEvent(new CustomEvent('__bridge_push_json', {
                            detail: { json: envelopeJSON, nonce: PUSH_NONCE }
                        }));
                    },
                    applyIntakeFrameJSON: function(frameJSON) {
                        dispatchIntakeFrameJSON(frameJSON);
                    },
                    sendCommandJSON: function(commandJSON) {
                        if (typeof commandJSON !== 'string' || commandJSON.length === 0) {
                            console.warn('[BridgeInternal] sendCommandJSON: commandJSON must be a non-empty string');
                            return;
                        }
                        window.webkit.messageHandlers.rpc.postMessage(commandJSON);
                    },
                    appendAgentEvents: function(events) {
                        document.dispatchEvent(new CustomEvent('__bridge_agent', {
                            detail: { events: events, nonce: PUSH_NONCE }
                        }));
                    },
                    response: function(id, result, error) {
                        document.dispatchEvent(new CustomEvent('__bridge_response', {
                            detail: { id: id, result: result, error: error, nonce: PUSH_NONCE }
                        }));
                    }
                };

                // Listen for commands from page world — validate nonce before forwarding to Swift.
                // Page world sends { jsonrpc, method, params, __nonce }.
                // Bridge world validates __nonce, strips it, and forwards the rest as stringified JSON.
                document.addEventListener('__bridge_command', function(event) {
                    const detail = event.detail;
                    if (!detail) {
                        console.warn('[BridgeBootstrap] Rejected __bridge_command: missing event detail');
                        return;
                    }
                    if (!detail.__nonce) {
                        console.warn('[BridgeBootstrap] Rejected __bridge_command: missing nonce');
                        return;
                    }
                    if (detail.__nonce !== BRIDGE_NONCE) {
                        console.warn('[BridgeBootstrap] Rejected __bridge_command: invalid nonce');
                        return;
                    }
                    // Strip nonce before forwarding to Swift
                    const { __nonce, ...payload } = detail;
                    if (payload.protocol !== undefined) {
                        console.warn('[BridgeBootstrap] Rejected __bridge_command: protocol RPC must use bridge world');
                        return;
                    }
                    if (typeof payload.method !== 'string' || !PAGE_WORLD_ALLOWED_COMMAND_METHODS.has(payload.method)) {
                        console.warn('[BridgeBootstrap] Rejected __bridge_command: method is not allowed from page world');
                        return;
                    }
                    payload.__bridgeOrigin = 'pageWorldLegacy';
                    window.webkit.messageHandlers.rpc.postMessage(JSON.stringify(payload));
                });

                // Listen for bridge.ready from page world
                document.addEventListener('__bridge_ready', function(event) {
                    // Relay to Swift — this triggers push plan start
                    window.webkit.messageHandlers.rpc.postMessage(
                        JSON.stringify({ jsonrpc: '2.0', method: 'bridge.ready', params: {} })
                    );
                });

                // Dispatch handshake to page world with push nonce.
                // Page world needs this to validate incoming push events.
                document.dispatchEvent(new CustomEvent('__bridge_handshake', {
                    detail: { pushNonce: PUSH_NONCE, telemetryConfig: TELEMETRY_CONFIG }
                }));

                // Replay handshake for late page-world listeners (P1 fix).
                // The initial __bridge_handshake fires at document start, but the React
                // bundle typically loads later and misses it. Page world can dispatch
                // __bridge_handshake_request to receive a replayed __bridge_handshake.
                document.addEventListener('__bridge_handshake_request', function() {
                    document.dispatchEvent(new CustomEvent('__bridge_handshake', {
                        detail: { pushNonce: PUSH_NONCE, telemetryConfig: TELEMETRY_CONFIG }
                    }));
                });
                document.addEventListener('__bridge_host_push_port_request', function() {
                    publishHostPushPort();
                });
                document.addEventListener('__bridge_host_intake_port_request', function() {
                    publishHostIntakePort();
                });
                document.addEventListener('__bridge_intake_replay_request', function() {
                    for (const frameJSON of PENDING_INTAKE_FRAME_JSON) {
                        postHostIntakeFrameJSON(frameJSON);
                        document.dispatchEvent(new CustomEvent('__bridge_intake_json', {
                            detail: { json: frameJSON, nonce: PUSH_NONCE }
                        }));
                    }
                });
                publishHostPushPort();
                publishHostIntakePort();

                // Set nonce attribute on documentElement for page world command sender
                document.documentElement.setAttribute('data-bridge-nonce', BRIDGE_NONCE);
                if (typeof REVIEW_PANE_ID === 'string' && typeof REVIEW_STREAM_ID === 'string') {
                    document.documentElement.setAttribute('data-bridge-review-pane-id', REVIEW_PANE_ID);
                    document.documentElement.setAttribute('data-bridge-review-stream-id', REVIEW_STREAM_ID);
                }
                if (WORKTREE_FILE_SOURCE_SPEC !== null) {
                    document.documentElement.setAttribute(
                        'data-bridge-worktree-file-source-spec',
                        JSON.stringify(WORKTREE_FILE_SOURCE_SPEC)
                    );
                }
            })();
            """
    }

    private static func encodedOptionalJSONString(_ value: String?) -> String {
        guard let value else {
            return "null"
        }
        return encodedJSONString(value)
    }

    private static func encodedJSONString(_ value: String) -> String {
        guard let data = try? JSONEncoder().encode(value),
            let json = String(data: data, encoding: .utf8)
        else {
            return "null"
        }
        return json
    }

    private static func encodedTelemetryConfigJSON(_ telemetryConfig: BridgeTelemetryBootstrapConfig?) -> String {
        guard let telemetryConfig else {
            return "null"
        }

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        guard let data = try? encoder.encode(telemetryConfig),
            let json = String(data: data, encoding: .utf8)
        else {
            return "null"
        }
        return json
    }

    private static func encodedWorktreeFileSourceSpecJSON(
        _ sourceSpec: BridgeWorktreeFileSurfaceSourceSpec?
    ) -> String {
        guard let sourceSpec else {
            return "null"
        }

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        guard let data = try? encoder.encode(sourceSpec),
            let json = String(data: data, encoding: .utf8)
        else {
            return "null"
        }
        return json
    }
    // swiftlint:enable function_body_length
}
