import Foundation
import GhosttyKit

extension Ghostty.ActionRouter {
    static let explicitlyRoutedTags: Set<GhosttyActionTag> = [
        .newTab,
        .ringBell,
        .setTitle,
        .setTabTitle,
        .pwd,
        .newSplit,
        .gotoSplit,
        .resizeSplit,
        .equalizeSplits,
        .toggleSplitZoom,
        .closeTab,
        .gotoTab,
        .moveTab,
        .sizeLimit,
        .initialSize,
        .cellSize,
        .desktopNotification,
        .promptTitle,
        .mouseShape,
        .mouseVisibility,
        .mouseOverLink,
        .rendererHealth,
        .secureInput,
        .keySequence,
        .keyTable,
        .colorChange,
        .reloadConfig,
        .configChange,
        .undo,
        .redo,
        .openURL,
        .progressReport,
        .commandFinished,
        .scrollbar,
        .startSearch,
        .endSearch,
        .searchTotal,
        .searchSelected,
        .readOnly,
        .copyTitleToClipboard,
    ]

    static let deferredTags: Set<GhosttyActionTag> = []

    static let interceptedTags: Set<GhosttyActionTag> = [
        .quit,
        .newWindow,
        .closeAllWindows,
        .toggleMaximize,
        .toggleFullscreen,
        .toggleTabOverview,
        .toggleWindowDecorations,
        .toggleQuickTerminal,
        .toggleCommandPalette,
        .toggleVisibility,
        .toggleBackgroundOpacity,
        .gotoWindow,
        .presentTerminal,
        .resetWindowSize,
        .inspector,
        .showGtkInspector,
        .renderInspector,
        .render,
        .openConfig,
        .quitTimer,
        .floatWindow,
        .closeWindow,
        .checkForUpdates,
        .showChildExited,
        .showOnScreenKeyboard,
    ]
}
